// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:53  dawn -> sunrise, widest step 0.032 in lightness
//   20:55  dusk -> night, widest step 0.032 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Blossom — Soft rose and plum. The lightest of the presets by day; its night end stays tinted rather than going neutral.
 */
export const blossom = defineThemeSystem({
  name: 'blossom',
  staticThemes: {
    light: {
      background: 'oklch(0.985 0.0074 350 / 1)',
      foreground: 'oklch(0.145 0.015 350 / 1)',
      surface: 'oklch(0.95 0.0074 350 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 350 / 1)',
      accent: 'oklch(0.46 0.1613 358 / 1)',
      accentForeground: 'oklch(0.985 0.0068 358 / 1)'
    },
    dark: {
      background: 'oklch(0.16 0.024 340 / 1)',
      foreground: 'oklch(0.985 0.0084 340 / 1)',
      surface: 'oklch(0.21 0.024 340 / 1)',
      surfaceForeground: 'oklch(0.985 0.0084 340 / 1)',
      accent: 'oklch(0.47 0.15 350 / 1)',
      accentForeground: 'oklch(0.985 0.0074 350 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.16 0.024 340 / 1)',
        foreground: 'oklch(0.985 0.0084 340 / 1)',
        surface: 'oklch(0.21 0.024 340 / 1)',
        surfaceForeground: 'oklch(0.985 0.0084 340 / 1)',
        accent: 'oklch(0.47 0.15 350 / 1)',
        accentForeground: 'oklch(0.985 0.0074 350 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.21 0.034 345 / 1)',
        foreground: 'oklch(0.985 0.0078 345 / 1)',
        surface: 'oklch(0.26 0.034 345 / 1)',
        surfaceForeground: 'oklch(0.985 0.0078 345 / 1)',
        accent: 'oklch(0.47 0.16 355 / 1)',
        accentForeground: 'oklch(0.985 0.007 355 / 1)'
      }
    },
    {
      minute: 353,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.54567 0.02526 349.41667 / 1)',
        foreground: 'oklch(0.985 0.0078 345 / 1)',
        surface: 'oklch(0.55813 0.02526 349.41667 / 1)',
        surfaceForeground: 'oklch(0.985 0.0078 345 / 1)',
        accent: 'oklch(0.47 0.16115 359.41667 / 1)',
        accentForeground: 'oklch(0.985 0.007 355 / 1)'
      }
    },
    {
      minute: 354,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.57733 0.02443 349.83333 / 1)',
        foreground: 'oklch(0.145 0.015 355 / 1)',
        surface: 'oklch(0.58625 0.02443 349.83333 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 355 / 1)',
        accent: 'oklch(0.47 0.16126 359.83333 / 1)',
        accentForeground: 'oklch(0.985 0.0065 5 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.97 0.0142 355 / 1)',
        foreground: 'oklch(0.145 0.015 355 / 1)',
        surface: 'oklch(0.935 0.0142 355 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 355 / 1)',
        accent: 'oklch(0.47 0.1626 5 / 1)',
        accentForeground: 'oklch(0.985 0.0065 5 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.985 0.0074 350 / 1)',
        foreground: 'oklch(0.145 0.015 350 / 1)',
        surface: 'oklch(0.95 0.0074 350 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 350 / 1)',
        accent: 'oklch(0.46 0.1613 358 / 1)',
        accentForeground: 'oklch(0.985 0.0068 358 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.965 0.016 348 / 1)',
        foreground: 'oklch(0.145 0.015 348 / 1)',
        surface: 'oklch(0.93 0.016 348 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 348 / 1)',
        accent: 'oklch(0.47 0.1633 2 / 1)',
        accentForeground: 'oklch(0.985 0.0066 2 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.94 0.026 342 / 1)',
        foreground: 'oklch(0.145 0.015 342 / 1)',
        surface: 'oklch(0.905 0.026 342 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 342 / 1)',
        accent: 'oklch(0.47 0.16 352 / 1)',
        accentForeground: 'oklch(0.985 0.0072 352 / 1)'
      }
    },
    {
      minute: 1255,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.5825 0.02508 341.08333 / 1)',
        foreground: 'oklch(0.145 0.015 342 / 1)',
        surface: 'oklch(0.58646 0.02508 341.08333 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 342 / 1)',
        accent: 'oklch(0.47 0.15542 351.08333 / 1)',
        accentForeground: 'oklch(0.985 0.0072 352 / 1)'
      }
    },
    {
      minute: 1256,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.55 0.025 341 / 1)',
        foreground: 'oklch(0.985 0.0084 340 / 1)',
        surface: 'oklch(0.5575 0.025 341 / 1)',
        surfaceForeground: 'oklch(0.985 0.0084 340 / 1)',
        accent: 'oklch(0.47 0.155 351 / 1)',
        accentForeground: 'oklch(0.985 0.0074 350 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.16 0.024 340 / 1)',
        foreground: 'oklch(0.985 0.0084 340 / 1)',
        surface: 'oklch(0.21 0.024 340 / 1)',
        surfaceForeground: 'oklch(0.985 0.0084 340 / 1)',
        accent: 'oklch(0.47 0.15 350 / 1)',
        accentForeground: 'oklch(0.985 0.0074 350 / 1)'
      }
    }
  ]
});

export default blossom;
