// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:42  dawn -> sunrise, widest step 0.265 in lightness
//   20:39  dusk -> night, widest step 0.264 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Contrast first — Every declared pair certified at AAA (7:1) across all 1,440 minutes. Time of day is carried by hue and chroma rather than lightness, because lightness is the budget contrast spends.
 */
export const contrastFirst = defineThemeSystem({
  name: 'contrast-first',
  staticThemes: {
    light: {
      background: 'oklch(0.995 0.004 100 / 1)',
      foreground: 'oklch(0.145 0.015 100 / 1)',
      surface: 'oklch(0.96 0.004 100 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 100 / 1)',
      accent: 'oklch(0.4 0.13 25 / 1)',
      accentForeground: 'oklch(0.985 0.0062 25 / 1)'
    },
    dark: {
      background: 'oklch(0.12 0.02 265 / 1)',
      foreground: 'oklch(0.985 0.006 265 / 1)',
      surface: 'oklch(0.17 0.02 265 / 1)',
      surfaceForeground: 'oklch(0.985 0.006 265 / 1)',
      accent: 'oklch(0.42 0.13 280 / 1)',
      accentForeground: 'oklch(0.985 0.0062 280 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AAA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AAA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AAA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.12 0.02 265 / 1)',
        foreground: 'oklch(0.985 0.006 265 / 1)',
        surface: 'oklch(0.17 0.02 265 / 1)',
        surfaceForeground: 'oklch(0.985 0.006 265 / 1)',
        accent: 'oklch(0.42 0.13 280 / 1)',
        accentForeground: 'oklch(0.985 0.0062 280 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.13 0.035 290 / 1)',
        foreground: 'oklch(0.985 0.0065 290 / 1)',
        surface: 'oklch(0.18 0.035 290 / 1)',
        surfaceForeground: 'oklch(0.985 0.0065 290 / 1)',
        accent: 'oklch(0.42 0.13 320 / 1)',
        accentForeground: 'oklch(0.985 0.0098 320 / 1)'
      }
    },
    {
      minute: 342,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.431 0.02492 339 / 1)',
        foreground: 'oklch(0.985 0.0065 290 / 1)',
        surface: 'oklch(0.45125 0.02492 339 / 1)',
        surfaceForeground: 'oklch(0.985 0.0065 290 / 1)',
        accent: 'oklch(0.42 0.12895 346.25 / 1)',
        accentForeground: 'oklch(0.985 0.0098 320 / 1)'
      }
    },
    {
      minute: 343,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.69617 0.01604 22.16667 / 1)',
        foreground: 'oklch(0.145 0.015 70 / 1)',
        surface: 'oklch(0.69021 0.01604 22.16667 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 70 / 1)',
        accent: 'oklch(0.42 0.12803 9.375 / 1)',
        accentForeground: 'oklch(0.985 0.0064 35 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.99 0.0062 70 / 1)',
        foreground: 'oklch(0.145 0.015 70 / 1)',
        surface: 'oklch(0.955 0.0062 70 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 70 / 1)',
        accent: 'oklch(0.42 0.127 35 / 1)',
        accentForeground: 'oklch(0.985 0.0064 35 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.995 0.004 100 / 1)',
        foreground: 'oklch(0.145 0.015 100 / 1)',
        surface: 'oklch(0.96 0.004 100 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 100 / 1)',
        accent: 'oklch(0.4 0.13 25 / 1)',
        accentForeground: 'oklch(0.985 0.0062 25 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.985 0.01 80 / 1)',
        foreground: 'oklch(0.145 0.015 80 / 1)',
        surface: 'oklch(0.95 0.01 80 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 80 / 1)',
        accent: 'oklch(0.41 0.13 30 / 1)',
        accentForeground: 'oklch(0.985 0.0063 30 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.975 0.0132 60 / 1)',
        foreground: 'oklch(0.145 0.015 60 / 1)',
        surface: 'oklch(0.94 0.0132 60 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 60 / 1)',
        accent: 'oklch(0.42 0.13 22 / 1)',
        accentForeground: 'oklch(0.985 0.0062 22 / 1)'
      }
    },
    {
      minute: 1239,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.69713 0.01541 9.625 / 1)',
        foreground: 'oklch(0.145 0.015 60 / 1)',
        surface: 'oklch(0.68975 0.01541 9.625 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 60 / 1)',
        accent: 'oklch(0.42 0.13 348.85 / 1)',
        accentForeground: 'oklch(0.985 0.0062 22 / 1)'
      }
    },
    {
      minute: 1240,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.4335 0.01751 321.83333 / 1)',
        foreground: 'oklch(0.985 0.006 265 / 1)',
        surface: 'oklch(0.45233 0.01751 321.83333 / 1)',
        surfaceForeground: 'oklch(0.985 0.006 265 / 1)',
        accent: 'oklch(0.42 0.13 317.4 / 1)',
        accentForeground: 'oklch(0.985 0.0062 280 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.12 0.02 265 / 1)',
        foreground: 'oklch(0.985 0.006 265 / 1)',
        surface: 'oklch(0.17 0.02 265 / 1)',
        surfaceForeground: 'oklch(0.985 0.006 265 / 1)',
        accent: 'oklch(0.42 0.13 280 / 1)',
        accentForeground: 'oklch(0.985 0.0062 280 / 1)'
      }
    }
  ]
});

export default contrastFirst;
