// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
// Background and accent arcs are design decisions; every other token is solved
// for a contrast target and clamped into the sRGB gamut, then certified across
// all 1,440 minutes by scripts/certify.mjs.
import { defineThemeSystem, holdThenSnap } from '../core.js';

/**
 * Contrast first — Every declared pair certified at AAA (7:1) across all 1,440 minutes. Time of day is carried by hue and chroma rather than lightness, because lightness is the budget contrast spends.
 */
const deepNight = {
  background: 'oklch(0.12 0.02 265 / 1)',
  foreground: 'oklch(0.8538 0.015 265 / 1)',
  surface: 'oklch(0.17 0.02 265 / 1)',
  surfaceForeground: 'oklch(0.8723 0.015 265 / 1)',
  accent: 'oklch(0.85 0.0648 280 / 1)',
  accentForeground: 'oklch(0.3357 0.01 280 / 1)'
};

const dawn = {
  background: 'oklch(0.13 0.035 290 / 1)',
  foreground: 'oklch(0.8566 0.015 290 / 1)',
  surface: 'oklch(0.18 0.035 290 / 1)',
  surfaceForeground: 'oklch(0.877 0.015 290 / 1)',
  accent: 'oklch(0.86 0.0966 320 / 1)',
  accentForeground: 'oklch(0.3382 0.01 320 / 1)'
};

const sunrise = {
  background: 'oklch(0.99 0.0062 70 / 1)',
  foreground: 'oklch(0.3057 0.015 70 / 1)',
  surface: 'oklch(0.955 0.0062 70 / 1)',
  surfaceForeground: 'oklch(0.2755 0.015 70 / 1)',
  accent: 'oklch(0.42 0.127 35 / 1)',
  accentForeground: 'oklch(0.9395 0.01 35 / 1)'
};

const midday = {
  background: 'oklch(0.995 0.004 100 / 1)',
  foreground: 'oklch(0.309 0.015 100 / 1)',
  surface: 'oklch(0.96 0.004 100 / 1)',
  surfaceForeground: 'oklch(0.2794 0.015 100 / 1)',
  accent: 'oklch(0.4 0.13 25 / 1)',
  accentForeground: 'oklch(0.91 0.01 25 / 1)'
};

const afternoon = {
  background: 'oklch(0.985 0.01 80 / 1)',
  foreground: 'oklch(0.3014 0.015 80 / 1)',
  surface: 'oklch(0.95 0.01 80 / 1)',
  surfaceForeground: 'oklch(0.2706 0.015 80 / 1)',
  accent: 'oklch(0.41 0.13 30 / 1)',
  accentForeground: 'oklch(0.9243 0.01 30 / 1)'
};

const dusk = {
  background: 'oklch(0.975 0.0132 60 / 1)',
  foreground: 'oklch(0.2932 0.015 60 / 1)',
  surface: 'oklch(0.94 0.0132 60 / 1)',
  surfaceForeground: 'oklch(0.2609 0.015 60 / 1)',
  accent: 'oklch(0.42 0.13 22 / 1)',
  accentForeground: 'oklch(0.9372 0.01 22 / 1)'
};

const eveningNight = {
  background: 'oklch(0.13 0.03 300 / 1)',
  foreground: 'oklch(0.8569 0.015 300 / 1)',
  surface: 'oklch(0.18 0.03 300 / 1)',
  surfaceForeground: 'oklch(0.8773 0.015 300 / 1)',
  accent: 'oklch(0.86 0.1 330 / 1)',
  accentForeground: 'oklch(0.3372 0.01 330 / 1)'
};

export const contrastFirst = defineThemeSystem({
  name: 'contrast-first',
  staticThemes: {
    light: midday,
    dark: deepNight
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AAA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AAA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AAA' }
    ]
  },
  stops: [
    { minute: 0, appearance: 'dark', phase: 'night', tokens: deepNight },
    { minute: 300, appearance: 'dark', phase: 'dawn', tokens: dawn },
    // Each appearance swap occupies a single minute, so the foreground and
    // background never cross while both are on screen.
    ...holdThenSnap({
      at: 390,
      from: dawn,
      to: sunrise,
      fromAppearance: 'dark',
      toAppearance: 'light',
      phase: 'dawn',
      nextPhase: 'sunrise'
    }),
    { minute: 720, appearance: 'light', phase: 'midday', tokens: midday },
    { minute: 990, appearance: 'light', phase: 'afternoon', tokens: afternoon },
    ...holdThenSnap({
      at: 1140,
      from: dusk,
      to: eveningNight,
      fromAppearance: 'light',
      toAppearance: 'dark',
      phase: 'dusk',
      nextPhase: 'night'
    })
  ]
});

export default contrastFirst;
