// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:05  dawn -> sunrise, widest step 0.796 in lightness
//   20:04  dusk -> night, widest step 0.791 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Contrast first — Every declared pair certified at AAA (7:1) across all 1,440 minutes. Time of day is carried by hue and chroma rather than lightness, because lightness is the budget contrast spends.
 */
export const contrastFirst = defineThemeSystem({
  name: 'contrast-first',
  staticThemes: {
    light: {
      background: 'oklch(0.995 0.004 100 / 1)',
      foreground: 'oklch(0.309 0.015 100 / 1)',
      surface: 'oklch(0.96 0.004 100 / 1)',
      surfaceForeground: 'oklch(0.2794 0.015 100 / 1)',
      accent: 'oklch(0.4 0.13 25 / 1)',
      accentForeground: 'oklch(0.91 0.01 25 / 1)'
    },
    dark: {
      background: 'oklch(0.12 0.02 265 / 1)',
      foreground: 'oklch(0.8538 0.015 265 / 1)',
      surface: 'oklch(0.17 0.02 265 / 1)',
      surfaceForeground: 'oklch(0.8723 0.015 265 / 1)',
      accent: 'oklch(0.85 0.0648 280 / 1)',
      accentForeground: 'oklch(0.3357 0.01 280 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AAA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AAA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AAA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.12 0.02 265 / 1)',
        foreground: 'oklch(0.8538 0.015 265 / 1)',
        surface: 'oklch(0.17 0.02 265 / 1)',
        surfaceForeground: 'oklch(0.8723 0.015 265 / 1)',
        accent: 'oklch(0.85 0.0648 280 / 1)',
        accentForeground: 'oklch(0.3357 0.01 280 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.13 0.035 290 / 1)',
        foreground: 'oklch(0.8566 0.015 290 / 1)',
        surface: 'oklch(0.18 0.035 290 / 1)',
        surfaceForeground: 'oklch(0.877 0.015 290 / 1)',
        accent: 'oklch(0.86 0.0966 320 / 1)',
        accentForeground: 'oklch(0.3382 0.01 320 / 1)'
      }
    },
    {
      minute: 305,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.16583 0.0338 295.83333 / 1)',
        foreground: 'oklch(0.8566 0.015 290 / 1)',
        surface: 'oklch(0.21229 0.0338 295.83333 / 1)',
        surfaceForeground: 'oklch(0.877 0.015 290 / 1)',
        accent: 'oklch(0.84167 0.09787 323.125 / 1)',
        accentForeground: 'oklch(0.3382 0.01 320 / 1)'
      }
    },
    {
      minute: 306,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.96133 0.00716 65.33333 / 1)',
        foreground: 'oklch(0.3057 0.015 70 / 1)',
        surface: 'oklch(0.92917 0.00716 65.33333 / 1)',
        surfaceForeground: 'oklch(0.2755 0.015 70 / 1)',
        accent: 'oklch(0.43467 0.12599 32.5 / 1)',
        accentForeground: 'oklch(0.9395 0.01 35 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.99 0.0062 70 / 1)',
        foreground: 'oklch(0.3057 0.015 70 / 1)',
        surface: 'oklch(0.955 0.0062 70 / 1)',
        surfaceForeground: 'oklch(0.2755 0.015 70 / 1)',
        accent: 'oklch(0.42 0.127 35 / 1)',
        accentForeground: 'oklch(0.9395 0.01 35 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.995 0.004 100 / 1)',
        foreground: 'oklch(0.309 0.015 100 / 1)',
        surface: 'oklch(0.96 0.004 100 / 1)',
        surfaceForeground: 'oklch(0.2794 0.015 100 / 1)',
        accent: 'oklch(0.4 0.13 25 / 1)',
        accentForeground: 'oklch(0.91 0.01 25 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.985 0.01 80 / 1)',
        foreground: 'oklch(0.3014 0.015 80 / 1)',
        surface: 'oklch(0.95 0.01 80 / 1)',
        surfaceForeground: 'oklch(0.2706 0.015 80 / 1)',
        accent: 'oklch(0.41 0.13 30 / 1)',
        accentForeground: 'oklch(0.9243 0.01 30 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.975 0.0132 60 / 1)',
        foreground: 'oklch(0.2932 0.015 60 / 1)',
        surface: 'oklch(0.94 0.0132 60 / 1)',
        surfaceForeground: 'oklch(0.2609 0.015 60 / 1)',
        accent: 'oklch(0.42 0.13 22 / 1)',
        accentForeground: 'oklch(0.9372 0.01 22 / 1)'
      }
    },
    {
      minute: 1204,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.9465 0.01343 54.83333 / 1)',
        foreground: 'oklch(0.2932 0.015 60 / 1)',
        surface: 'oklch(0.91433 0.01343 54.83333 / 1)',
        surfaceForeground: 'oklch(0.2609 0.015 60 / 1)',
        accent: 'oklch(0.43433 0.12783 18.6 / 1)',
        accentForeground: 'oklch(0.9372 0.01 22 / 1)'
      }
    },
    {
      minute: 1205,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.15563 0.01972 271.45833 / 1)',
        foreground: 'oklch(0.8538 0.015 265 / 1)',
        surface: 'oklch(0.20208 0.01972 271.45833 / 1)',
        surfaceForeground: 'oklch(0.8723 0.015 265 / 1)',
        accent: 'oklch(0.83208 0.06752 284.25 / 1)',
        accentForeground: 'oklch(0.3357 0.01 280 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.12 0.02 265 / 1)',
        foreground: 'oklch(0.8538 0.015 265 / 1)',
        surface: 'oklch(0.17 0.02 265 / 1)',
        surfaceForeground: 'oklch(0.8723 0.015 265 / 1)',
        accent: 'oklch(0.85 0.0648 280 / 1)',
        accentForeground: 'oklch(0.3357 0.01 280 / 1)'
      }
    }
  ]
});

export default contrastFirst;
