// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
// Background and accent arcs are design decisions; every other token is solved
// for a contrast target and clamped into the sRGB gamut, then certified across
// all 1,440 minutes by scripts/certify.mjs.
import { defineThemeSystem, holdThenSnap } from '../core.js';

/**
 * Dawn to dusk — Warm arc: indigo night, amber sunrise, neutral midday, ember dusk.
 */
const deepNight = {
  background: 'oklch(0.15 0.028 265 / 1)',
  foreground: 'oklch(0.7549 0.015 265 / 1)',
  surface: 'oklch(0.2 0.028 265 / 1)',
  surfaceForeground: 'oklch(0.7784 0.015 265 / 1)',
  accent: 'oklch(0.78 0.105 292 / 1)',
  accentForeground: 'oklch(0.328 0.01 292 / 1)'
};

const dawn = {
  background: 'oklch(0.21 0.045 285 / 1)',
  foreground: 'oklch(0.7835 0.015 285 / 1)',
  surface: 'oklch(0.26 0.045 285 / 1)',
  surfaceForeground: 'oklch(0.8215 0.015 285 / 1)',
  accent: 'oklch(0.8 0.12 320 / 1)',
  accentForeground: 'oklch(0.3412 0.01 320 / 1)'
};

const sunrise = {
  background: 'oklch(0.97 0.018 68 / 1)',
  foreground: 'oklch(0.3848 0.015 68 / 1)',
  surface: 'oklch(0.935 0.018 68 / 1)',
  surfaceForeground: 'oklch(0.3593 0.015 68 / 1)',
  accent: 'oklch(0.53 0.1494 38 / 1)',
  accentForeground: 'oklch(1 0 38 / 1)'
};

const midday = {
  background: 'oklch(0.985 0.006 95 / 1)',
  foreground: 'oklch(0.395 0.015 95 / 1)',
  surface: 'oklch(0.95 0.006 95 / 1)',
  surfaceForeground: 'oklch(0.3702 0.015 95 / 1)',
  accent: 'oklch(0.5 0.14 30 / 1)',
  accentForeground: 'oklch(0.9771 0.0097 30 / 1)'
};

const afternoon = {
  background: 'oklch(0.955 0.016 78 / 1)',
  foreground: 'oklch(0.3741 0.015 78 / 1)',
  surface: 'oklch(0.92 0.016 78 / 1)',
  surfaceForeground: 'oklch(0.3478 0.015 78 / 1)',
  accent: 'oklch(0.51 0.15 35 / 1)',
  accentForeground: 'oklch(0.9905 0.0041 35 / 1)'
};

const dusk = {
  background: 'oklch(0.925 0.026 58 / 1)',
  foreground: 'oklch(0.3514 0.015 58 / 1)',
  surface: 'oklch(0.89 0.026 58 / 1)',
  surfaceForeground: 'oklch(0.3232 0.015 58 / 1)',
  accent: 'oklch(0.52 0.15 28 / 1)',
  accentForeground: 'oklch(1 0 28 / 1)'
};

const eveningNight = {
  background: 'oklch(0.19 0.04 300 / 1)',
  foreground: 'oklch(0.7721 0.015 300 / 1)',
  surface: 'oklch(0.24 0.04 300 / 1)',
  surfaceForeground: 'oklch(0.8048 0.015 300 / 1)',
  accent: 'oklch(0.79 0.12 330 / 1)',
  accentForeground: 'oklch(0.3314 0.01 330 / 1)'
};

export const dawnToDusk = defineThemeSystem({
  name: 'dawn-to-dusk',
  staticThemes: {
    light: midday,
    dark: deepNight
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    { minute: 0, appearance: 'dark', phase: 'night', tokens: deepNight },
    { minute: 300, appearance: 'dark', phase: 'dawn', tokens: dawn },
    // Each appearance swap occupies a single minute, so the foreground and
    // background never cross while both are on screen.
    ...holdThenSnap({
      at: 390,
      from: dawn,
      to: sunrise,
      fromAppearance: 'dark',
      toAppearance: 'light',
      phase: 'dawn',
      nextPhase: 'sunrise'
    }),
    { minute: 720, appearance: 'light', phase: 'midday', tokens: midday },
    { minute: 990, appearance: 'light', phase: 'afternoon', tokens: afternoon },
    ...holdThenSnap({
      at: 1140,
      from: dusk,
      to: eveningNight,
      fromAppearance: 'light',
      toAppearance: 'dark',
      phase: 'dusk',
      nextPhase: 'night'
    })
  ]
});

export default dawnToDusk;
