// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:31  dawn -> sunrise, widest step 0.412 in lightness
//   20:30  dusk -> night, widest step 0.368 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Dawn to dusk — Warm arc: indigo night, amber sunrise, neutral midday, ember dusk.
 */
export const dawnToDusk = defineThemeSystem({
  name: 'dawn-to-dusk',
  staticThemes: {
    light: {
      background: 'oklch(0.985 0.006 95 / 1)',
      foreground: 'oklch(0.395 0.015 95 / 1)',
      surface: 'oklch(0.95 0.006 95 / 1)',
      surfaceForeground: 'oklch(0.3702 0.015 95 / 1)',
      accent: 'oklch(0.5 0.14 30 / 1)',
      accentForeground: 'oklch(0.9771 0.0097 30 / 1)'
    },
    dark: {
      background: 'oklch(0.15 0.028 265 / 1)',
      foreground: 'oklch(0.7549 0.015 265 / 1)',
      surface: 'oklch(0.2 0.028 265 / 1)',
      surfaceForeground: 'oklch(0.7784 0.015 265 / 1)',
      accent: 'oklch(0.78 0.105 292 / 1)',
      accentForeground: 'oklch(0.328 0.01 292 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.028 265 / 1)',
        foreground: 'oklch(0.7549 0.015 265 / 1)',
        surface: 'oklch(0.2 0.028 265 / 1)',
        surfaceForeground: 'oklch(0.7784 0.015 265 / 1)',
        accent: 'oklch(0.78 0.105 292 / 1)',
        accentForeground: 'oklch(0.328 0.01 292 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.21 0.045 285 / 1)',
        foreground: 'oklch(0.7835 0.015 285 / 1)',
        surface: 'oklch(0.26 0.045 285 / 1)',
        surfaceForeground: 'oklch(0.8215 0.015 285 / 1)',
        accent: 'oklch(0.8 0.12 320 / 1)',
        accentForeground: 'oklch(0.3412 0.01 320 / 1)'
      }
    },
    {
      minute: 331,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.40633 0.03802 321.94167 / 1)',
        foreground: 'oklch(0.7835 0.015 285 / 1)',
        surface: 'oklch(0.43438 0.03802 321.94167 / 1)',
        surfaceForeground: 'oklch(0.8215 0.015 285 / 1)',
        accent: 'oklch(0.73025 0.12759 340.15 / 1)',
        accentForeground: 'oklch(0.3412 0.01 320 / 1)'
      }
    },
    {
      minute: 332,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.818 0.0234 39.4 / 1)',
        foreground: 'oklch(0.3848 0.015 68 / 1)',
        surface: 'oklch(0.8 0.0234 39.4 / 1)',
        surfaceForeground: 'oklch(0.3593 0.015 68 / 1)',
        accent: 'oklch(0.584 0.14352 22.4 / 1)',
        accentForeground: 'oklch(1 0 38 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.97 0.018 68 / 1)',
        foreground: 'oklch(0.3848 0.015 68 / 1)',
        surface: 'oklch(0.935 0.018 68 / 1)',
        surfaceForeground: 'oklch(0.3593 0.015 68 / 1)',
        accent: 'oklch(0.53 0.1494 38 / 1)',
        accentForeground: 'oklch(1 0 38 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.985 0.006 95 / 1)',
        foreground: 'oklch(0.395 0.015 95 / 1)',
        surface: 'oklch(0.95 0.006 95 / 1)',
        surfaceForeground: 'oklch(0.3702 0.015 95 / 1)',
        accent: 'oklch(0.5 0.14 30 / 1)',
        accentForeground: 'oklch(0.9771 0.0097 30 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.955 0.016 78 / 1)',
        foreground: 'oklch(0.3741 0.015 78 / 1)',
        surface: 'oklch(0.92 0.016 78 / 1)',
        surfaceForeground: 'oklch(0.3478 0.015 78 / 1)',
        accent: 'oklch(0.51 0.15 35 / 1)',
        accentForeground: 'oklch(0.9905 0.0041 35 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.925 0.026 58 / 1)',
        foreground: 'oklch(0.3514 0.015 58 / 1)',
        surface: 'oklch(0.89 0.026 58 / 1)',
        surfaceForeground: 'oklch(0.3232 0.015 58 / 1)',
        accent: 'oklch(0.52 0.15 28 / 1)',
        accentForeground: 'oklch(1 0 28 / 1)'
      }
    },
    {
      minute: 1230,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.73125 0.0265 19.75 / 1)',
        foreground: 'oklch(0.3514 0.015 58 / 1)',
        surface: 'oklch(0.7175 0.0265 19.75 / 1)',
        surfaceForeground: 'oklch(0.3232 0.015 58 / 1)',
        accent: 'oklch(0.585 0.13875 4 / 1)',
        accentForeground: 'oklch(1 0 28 / 1)'
      }
    },
    {
      minute: 1231,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.36313 0.02745 307.075 / 1)',
        foreground: 'oklch(0.7549 0.015 265 / 1)',
        surface: 'oklch(0.38975 0.02745 307.075 / 1)',
        surfaceForeground: 'oklch(0.7784 0.015 265 / 1)',
        accent: 'oklch(0.7085 0.11738 318.4 / 1)',
        accentForeground: 'oklch(0.328 0.01 292 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.028 265 / 1)',
        foreground: 'oklch(0.7549 0.015 265 / 1)',
        surface: 'oklch(0.2 0.028 265 / 1)',
        surfaceForeground: 'oklch(0.7784 0.015 265 / 1)',
        accent: 'oklch(0.78 0.105 292 / 1)',
        accentForeground: 'oklch(0.328 0.01 292 / 1)'
      }
    }
  ]
});

export default dawnToDusk;
