// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:53  dawn -> sunrise, widest step 0.038 in lightness
//   20:53  dusk -> night, widest step 0.032 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Dawn to dusk — Warm arc: indigo night, amber sunrise, neutral midday, ember dusk.
 */
export const dawnToDusk = defineThemeSystem({
  name: 'dawn-to-dusk',
  staticThemes: {
    light: {
      background: 'oklch(0.985 0.006 95 / 1)',
      foreground: 'oklch(0.145 0.015 95 / 1)',
      surface: 'oklch(0.95 0.006 95 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 95 / 1)',
      accent: 'oklch(0.5 0.14 30 / 1)',
      accentForeground: 'oklch(0.985 0.0063 30 / 1)'
    },
    dark: {
      background: 'oklch(0.15 0.028 265 / 1)',
      foreground: 'oklch(0.985 0.006 265 / 1)',
      surface: 'oklch(0.2 0.028 265 / 1)',
      surfaceForeground: 'oklch(0.985 0.006 265 / 1)',
      accent: 'oklch(0.5038 0.15 292 / 1)',
      accentForeground: 'oklch(0.985 0.0066 292 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.028 265 / 1)',
        foreground: 'oklch(0.985 0.006 265 / 1)',
        surface: 'oklch(0.2 0.028 265 / 1)',
        surfaceForeground: 'oklch(0.985 0.006 265 / 1)',
        accent: 'oklch(0.5038 0.15 292 / 1)',
        accentForeground: 'oklch(0.985 0.0066 292 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.21 0.045 285 / 1)',
        foreground: 'oklch(0.985 0.0063 285 / 1)',
        surface: 'oklch(0.26 0.045 285 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 285 / 1)',
        accent: 'oklch(0.5091 0.16 320 / 1)',
        accentForeground: 'oklch(0.985 0.0098 320 / 1)'
      }
    },
    {
      minute: 353,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.54567 0.03308 348.15833 / 1)',
        foreground: 'oklch(0.985 0.0063 285 / 1)',
        surface: 'oklch(0.55813 0.03308 348.15833 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 285 / 1)',
        accent: 'oklch(0.50716 0.15218 354.45 / 1)',
        accentForeground: 'oklch(0.985 0.0098 320 / 1)'
      }
    },
    {
      minute: 354,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.58367 0.03173 355.30833 / 1)',
        foreground: 'oklch(0.145 0.015 68 / 1)',
        surface: 'oklch(0.59188 0.03173 355.30833 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 68 / 1)',
        accent: 'oklch(0.50694 0.1513 358.35 / 1)',
        accentForeground: 'oklch(0.985 0.0065 38 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.97 0.018 68 / 1)',
        foreground: 'oklch(0.145 0.015 68 / 1)',
        surface: 'oklch(0.935 0.018 68 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 68 / 1)',
        accent: 'oklch(0.5047 0.1423 38 / 1)',
        accentForeground: 'oklch(0.985 0.0065 38 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.985 0.006 95 / 1)',
        foreground: 'oklch(0.145 0.015 95 / 1)',
        surface: 'oklch(0.95 0.006 95 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 95 / 1)',
        accent: 'oklch(0.5 0.14 30 / 1)',
        accentForeground: 'oklch(0.985 0.0063 30 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.955 0.016 78 / 1)',
        foreground: 'oklch(0.145 0.015 78 / 1)',
        surface: 'oklch(0.92 0.016 78 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 78 / 1)',
        accent: 'oklch(0.5061 0.15 35 / 1)',
        accentForeground: 'oklch(0.985 0.0064 35 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.925 0.026 58 / 1)',
        foreground: 'oklch(0.145 0.015 58 / 1)',
        surface: 'oklch(0.89 0.026 58 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 58 / 1)',
        accent: 'oklch(0.507 0.15 28 / 1)',
        accentForeground: 'oklch(0.985 0.0063 28 / 1)'
      }
    },
    {
      minute: 1253,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.58271 0.02688 350.425 / 1)',
        foreground: 'oklch(0.145 0.015 58 / 1)',
        surface: 'oklch(0.58525 0.02688 350.425 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 58 / 1)',
        accent: 'oklch(0.50559 0.15 345.6 / 1)',
        accentForeground: 'oklch(0.985 0.0063 28 / 1)'
      }
    },
    {
      minute: 1254,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.55042 0.02697 344.05 / 1)',
        foreground: 'oklch(0.985 0.006 265 / 1)',
        surface: 'oklch(0.5565 0.02697 344.05 / 1)',
        surfaceForeground: 'oklch(0.985 0.006 265 / 1)',
        accent: 'oklch(0.50545 0.15 341.6 / 1)',
        accentForeground: 'oklch(0.985 0.0066 292 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.028 265 / 1)',
        foreground: 'oklch(0.985 0.006 265 / 1)',
        surface: 'oklch(0.2 0.028 265 / 1)',
        surfaceForeground: 'oklch(0.985 0.006 265 / 1)',
        accent: 'oklch(0.5038 0.15 292 / 1)',
        accentForeground: 'oklch(0.985 0.0066 292 / 1)'
      }
    }
  ]
});

export default dawnToDusk;
