// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:52  dawn -> sunrise, widest step 0.036 in lightness
//   20:54  dusk -> night, widest step 0.031 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Ember — Deep warm amber throughout, with a night end closer to charcoal than to black. Reads as lamplight rather than daylight.
 */
export const ember = defineThemeSystem({
  name: 'ember',
  staticThemes: {
    light: {
      background: 'oklch(0.975 0.014 72 / 1)',
      foreground: 'oklch(0.145 0.015 72 / 1)',
      surface: 'oklch(0.94 0.014 72 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 72 / 1)',
      accent: 'oklch(0.45 0.1269 38 / 1)',
      accentForeground: 'oklch(0.985 0.0065 38 / 1)'
    },
    dark: {
      background: 'oklch(0.17 0.022 35 / 1)',
      foreground: 'oklch(0.985 0.0064 35 / 1)',
      surface: 'oklch(0.22 0.022 35 / 1)',
      surfaceForeground: 'oklch(0.985 0.0064 35 / 1)',
      accent: 'oklch(0.47 0.15 28 / 1)',
      accentForeground: 'oklch(0.985 0.0063 28 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.17 0.022 35 / 1)',
        foreground: 'oklch(0.985 0.0064 35 / 1)',
        surface: 'oklch(0.22 0.022 35 / 1)',
        surfaceForeground: 'oklch(0.985 0.0064 35 / 1)',
        accent: 'oklch(0.47 0.15 28 / 1)',
        accentForeground: 'oklch(0.985 0.0063 28 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.23 0.034 30 / 1)',
        foreground: 'oklch(0.985 0.0063 30 / 1)',
        surface: 'oklch(0.28 0.034 30 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 30 / 1)',
        accent: 'oklch(0.47 0.16 25 / 1)',
        accentForeground: 'oklch(0.985 0.0062 25 / 1)'
      }
    },
    {
      minute: 352,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.54417 0.0291 40.83333 / 1)',
        foreground: 'oklch(0.985 0.0063 30 / 1)',
        surface: 'oklch(0.55733 0.0291 40.83333 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 30 / 1)',
        accent: 'oklch(0.46567 0.15575 28.03333 / 1)',
        accentForeground: 'oklch(0.985 0.0062 25 / 1)'
      }
    },
    {
      minute: 353,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.58042 0.02854 42.08333 / 1)',
        foreground: 'oklch(0.145 0.015 55 / 1)',
        surface: 'oklch(0.58933 0.02854 42.08333 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 55 / 1)',
        accent: 'oklch(0.46517 0.15526 28.38333 / 1)',
        accentForeground: 'oklch(0.985 0.0063 32 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.955 0.0227 55 / 1)',
        foreground: 'oklch(0.145 0.015 55 / 1)',
        surface: 'oklch(0.92 0.0227 55 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 55 / 1)',
        accent: 'oklch(0.46 0.1502 32 / 1)',
        accentForeground: 'oklch(0.985 0.0063 32 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.975 0.014 72 / 1)',
        foreground: 'oklch(0.145 0.015 72 / 1)',
        surface: 'oklch(0.94 0.014 72 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 72 / 1)',
        accent: 'oklch(0.45 0.1269 38 / 1)',
        accentForeground: 'oklch(0.985 0.0065 38 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.95 0.022 60 / 1)',
        foreground: 'oklch(0.145 0.015 60 / 1)',
        surface: 'oklch(0.915 0.022 60 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 60 / 1)',
        accent: 'oklch(0.46 0.1462 33 / 1)',
        accentForeground: 'oklch(0.985 0.0063 33 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.915 0.036 42 / 1)',
        foreground: 'oklch(0.145 0.015 42 / 1)',
        surface: 'oklch(0.88 0.036 42 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 42 / 1)',
        accent: 'oklch(0.47 0.16 26 / 1)',
        accentForeground: 'oklch(0.985 0.0062 26 / 1)'
      }
    },
    {
      minute: 1254,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.57975 0.0297 38.85 / 1)',
        foreground: 'oklch(0.145 0.015 42 / 1)',
        surface: 'oklch(0.583 0.0297 38.85 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 42 / 1)',
        accent: 'oklch(0.47 0.1555 26.9 / 1)',
        accentForeground: 'oklch(0.985 0.0062 26 / 1)'
      }
    },
    {
      minute: 1255,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.54871 0.02912 38.55833 / 1)',
        foreground: 'oklch(0.985 0.0064 35 / 1)',
        surface: 'oklch(0.5555 0.02912 38.55833 / 1)',
        surfaceForeground: 'oklch(0.985 0.0064 35 / 1)',
        accent: 'oklch(0.47 0.15508 26.98333 / 1)',
        accentForeground: 'oklch(0.985 0.0063 28 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.17 0.022 35 / 1)',
        foreground: 'oklch(0.985 0.0064 35 / 1)',
        surface: 'oklch(0.22 0.022 35 / 1)',
        surfaceForeground: 'oklch(0.985 0.0064 35 / 1)',
        accent: 'oklch(0.47 0.15 28 / 1)',
        accentForeground: 'oklch(0.985 0.0063 28 / 1)'
      }
    }
  ]
});

export default ember;
