// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:54  dawn -> sunrise, widest step 0.032 in lightness
//   20:54  dusk -> night, widest step 0.026 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Forest — Muted green and moss, low chroma throughout. sRGB has little room for saturated green at low lightness, so the accent leans toward teal as it darkens.
 */
export const forest = defineThemeSystem({
  name: 'forest',
  staticThemes: {
    light: {
      background: 'oklch(0.98 0.01 140 / 1)',
      foreground: 'oklch(0.145 0.015 140 / 1)',
      surface: 'oklch(0.945 0.01 140 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 140 / 1)',
      accent: 'oklch(0.45 0.1067 150 / 1)',
      accentForeground: 'oklch(0.985 0.01 150 / 1)'
    },
    dark: {
      background: 'oklch(0.15 0.018 160 / 1)',
      foreground: 'oklch(0.985 0.015 160 / 1)',
      surface: 'oklch(0.2 0.018 160 / 1)',
      surfaceForeground: 'oklch(0.985 0.015 160 / 1)',
      accent: 'oklch(0.45 0.0731 175 / 1)',
      accentForeground: 'oklch(0.985 0.01 175 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.018 160 / 1)',
        foreground: 'oklch(0.985 0.015 160 / 1)',
        surface: 'oklch(0.2 0.018 160 / 1)',
        surfaceForeground: 'oklch(0.985 0.015 160 / 1)',
        accent: 'oklch(0.45 0.0731 175 / 1)',
        accentForeground: 'oklch(0.985 0.01 175 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.2 0.026 155 / 1)',
        foreground: 'oklch(0.985 0.015 155 / 1)',
        surface: 'oklch(0.25 0.026 155 / 1)',
        surfaceForeground: 'oklch(0.985 0.015 155 / 1)',
        accent: 'oklch(0.45 0.0767 170 / 1)',
        accentForeground: 'oklch(0.985 0.01 170 / 1)'
      }
    },
    {
      minute: 354,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.54425 0.0215 143.75 / 1)',
        foreground: 'oklch(0.985 0.015 155 / 1)',
        surface: 'oklch(0.556 0.0215 143.75 / 1)',
        surfaceForeground: 'oklch(0.985 0.015 155 / 1)',
        accent: 'oklch(0.45 0.0853 163.25 / 1)',
        accentForeground: 'oklch(0.985 0.01 170 / 1)'
      }
    },
    {
      minute: 355,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.57613 0.02108 142.70833 / 1)',
        foreground: 'oklch(0.145 0.015 130 / 1)',
        surface: 'oklch(0.58433 0.02108 142.70833 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 130 / 1)',
        accent: 'oklch(0.45 0.08609 162.625 / 1)',
        accentForeground: 'oklch(0.985 0.01 155 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.965 0.016 130 / 1)',
        foreground: 'oklch(0.145 0.015 130 / 1)',
        surface: 'oklch(0.93 0.016 130 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 130 / 1)',
        accent: 'oklch(0.45 0.0958 155 / 1)',
        accentForeground: 'oklch(0.985 0.01 155 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.98 0.01 140 / 1)',
        foreground: 'oklch(0.145 0.015 140 / 1)',
        surface: 'oklch(0.945 0.01 140 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 140 / 1)',
        accent: 'oklch(0.45 0.1067 150 / 1)',
        accentForeground: 'oklch(0.985 0.01 150 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.955 0.016 135 / 1)',
        foreground: 'oklch(0.145 0.015 135 / 1)',
        surface: 'oklch(0.92 0.016 135 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 135 / 1)',
        accent: 'oklch(0.45 0.1019 152 / 1)',
        accentForeground: 'oklch(0.985 0.01 152 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.925 0.024 145 / 1)',
        foreground: 'oklch(0.145 0.015 145 / 1)',
        surface: 'oklch(0.89 0.024 145 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 145 / 1)',
        accent: 'oklch(0.45 0.085 162 / 1)',
        accentForeground: 'oklch(0.985 0.01 162 / 1)'
      }
    },
    {
      minute: 1254,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.57625 0.0213 151.75 / 1)',
        foreground: 'oklch(0.145 0.015 145 / 1)',
        surface: 'oklch(0.5795 0.0213 151.75 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 145 / 1)',
        accent: 'oklch(0.45 0.07965 167.85 / 1)',
        accentForeground: 'oklch(0.985 0.01 162 / 1)'
      }
    },
    {
      minute: 1255,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.55042 0.0211 152.25 / 1)',
        foreground: 'oklch(0.985 0.015 160 / 1)',
        surface: 'oklch(0.5565 0.0211 152.25 / 1)',
        surfaceForeground: 'oklch(0.985 0.015 160 / 1)',
        accent: 'oklch(0.45 0.07925 168.28333 / 1)',
        accentForeground: 'oklch(0.985 0.01 175 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.018 160 / 1)',
        foreground: 'oklch(0.985 0.015 160 / 1)',
        surface: 'oklch(0.2 0.018 160 / 1)',
        surfaceForeground: 'oklch(0.985 0.015 160 / 1)',
        accent: 'oklch(0.45 0.0731 175 / 1)',
        accentForeground: 'oklch(0.985 0.01 175 / 1)'
      }
    }
  ]
});

export default forest;
