// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:55  dawn -> sunrise, widest step 0.032 in lightness
//   20:54  dusk -> night, widest step 0.026 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Meridian — Neutral and quiet: hue barely moves across the day, so the only thing that changes is the light. The default when a theme should not have opinions.
 */
export const meridian = defineThemeSystem({
  name: 'meridian',
  staticThemes: {
    light: {
      background: 'oklch(0.985 0.002 250 / 1)',
      foreground: 'oklch(0.145 0.015 250 / 1)',
      surface: 'oklch(0.95 0.002 250 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 250 / 1)',
      accent: 'oklch(0.45 0.1234 254 / 1)',
      accentForeground: 'oklch(0.985 0.0062 254 / 1)'
    },
    dark: {
      background: 'oklch(0.14 0.006 250 / 1)',
      foreground: 'oklch(0.985 0.0063 250 / 1)',
      surface: 'oklch(0.19 0.006 250 / 1)',
      surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
      accent: 'oklch(0.46 0.1121 250 / 1)',
      accentForeground: 'oklch(0.985 0.0063 250 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.14 0.006 250 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.19 0.006 250 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.46 0.1121 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.19 0.008 250 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.24 0.008 250 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.46 0.1121 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 355,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.54521 0.00617 250 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.55625 0.00617 250 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.46 0.11503 250.91667 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 356,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.5775 0.006 250 / 1)',
        foreground: 'oklch(0.145 0.015 250 / 1)',
        surface: 'oklch(0.585 0.006 250 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 250 / 1)',
        accent: 'oklch(0.46 0.1153 251 / 1)',
        accentForeground: 'oklch(0.985 0.0063 252 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.965 0.004 250 / 1)',
        foreground: 'oklch(0.145 0.015 250 / 1)',
        surface: 'oklch(0.93 0.004 250 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 250 / 1)',
        accent: 'oklch(0.46 0.1185 252 / 1)',
        accentForeground: 'oklch(0.985 0.0063 252 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.985 0.002 250 / 1)',
        foreground: 'oklch(0.145 0.015 250 / 1)',
        surface: 'oklch(0.95 0.002 250 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 250 / 1)',
        accent: 'oklch(0.45 0.1234 254 / 1)',
        accentForeground: 'oklch(0.985 0.0062 254 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.96 0.004 250 / 1)',
        foreground: 'oklch(0.145 0.015 250 / 1)',
        surface: 'oklch(0.925 0.004 250 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 250 / 1)',
        accent: 'oklch(0.46 0.1185 252 / 1)',
        accentForeground: 'oklch(0.985 0.0063 252 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.93 0.008 250 / 1)',
        foreground: 'oklch(0.145 0.015 250 / 1)',
        surface: 'oklch(0.895 0.008 250 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 250 / 1)',
        accent: 'oklch(0.46 0.1121 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 1254,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.5745 0.0071 250 / 1)',
        foreground: 'oklch(0.145 0.015 250 / 1)',
        surface: 'oklch(0.57775 0.0071 250 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 250 / 1)',
        accent: 'oklch(0.46 0.1121 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 1255,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.54817 0.00703 250 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.55425 0.00703 250 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.46 0.1121 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.14 0.006 250 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.19 0.006 250 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.46 0.1121 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    }
  ]
});

export default meridian;
