// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   06:02  dawn -> sunrise, widest step 0.024 in lightness
//   20:49  dusk -> night, widest step 0.025 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Nocturne — Eye-comforting: the night end is dim and warm rather than blue, and midday stops short of paper white. For long sessions and dark rooms.
 */
export const nocturne = defineThemeSystem({
  name: 'nocturne',
  staticThemes: {
    light: {
      background: 'oklch(0.93 0.01 75 / 1)',
      foreground: 'oklch(0.145 0.015 75 / 1)',
      surface: 'oklch(0.895 0.01 75 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 75 / 1)',
      accent: 'oklch(0.45 0.1269 38 / 1)',
      accentForeground: 'oklch(0.985 0.0065 38 / 1)'
    },
    dark: {
      background: 'oklch(0.13 0.012 45 / 1)',
      foreground: 'oklch(0.985 0.0068 45 / 1)',
      surface: 'oklch(0.18 0.012 45 / 1)',
      surfaceForeground: 'oklch(0.985 0.0068 45 / 1)',
      accent: 'oklch(0.46 0.0981 55 / 1)',
      accentForeground: 'oklch(0.985 0.0074 55 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.13 0.012 45 / 1)',
        foreground: 'oklch(0.985 0.0068 45 / 1)',
        surface: 'oklch(0.18 0.012 45 / 1)',
        surfaceForeground: 'oklch(0.985 0.0068 45 / 1)',
        accent: 'oklch(0.46 0.0981 55 / 1)',
        accentForeground: 'oklch(0.985 0.0074 55 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.18 0.02 40 / 1)',
        foreground: 'oklch(0.985 0.0065 40 / 1)',
        surface: 'oklch(0.23 0.02 40 / 1)',
        surfaceForeground: 'oklch(0.985 0.0065 40 / 1)',
        accent: 'oklch(0.46 0.1133 45 / 1)',
        accentForeground: 'oklch(0.985 0.0068 45 / 1)'
      }
    },
    {
      minute: 362,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.552 0.01793 51.36667 / 1)',
        foreground: 'oklch(0.985 0.0065 40 / 1)',
        surface: 'oklch(0.55808 0.01793 51.36667 / 1)',
        surfaceForeground: 'oklch(0.985 0.0065 40 / 1)',
        accent: 'oklch(0.46 0.11898 42.41667 / 1)',
        accentForeground: 'oklch(0.985 0.0068 45 / 1)'
      }
    },
    {
      minute: 363,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.576 0.0178 52.1 / 1)',
        foreground: 'oklch(0.145 0.015 62 / 1)',
        surface: 'oklch(0.57925 0.0178 52.1 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 62 / 1)',
        accent: 'oklch(0.46 0.11935 42.25 / 1)',
        accentForeground: 'oklch(0.985 0.0065 40 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.9 0.016 62 / 1)',
        foreground: 'oklch(0.145 0.015 62 / 1)',
        surface: 'oklch(0.865 0.016 62 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 62 / 1)',
        accent: 'oklch(0.46 0.1243 40 / 1)',
        accentForeground: 'oklch(0.985 0.0065 40 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.93 0.01 75 / 1)',
        foreground: 'oklch(0.145 0.015 75 / 1)',
        surface: 'oklch(0.895 0.01 75 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 75 / 1)',
        accent: 'oklch(0.45 0.1269 38 / 1)',
        accentForeground: 'oklch(0.985 0.0065 38 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.915 0.014 68 / 1)',
        foreground: 'oklch(0.145 0.015 68 / 1)',
        surface: 'oklch(0.88 0.014 68 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 68 / 1)',
        accent: 'oklch(0.46 0.1196 42 / 1)',
        accentForeground: 'oklch(0.985 0.0066 42 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.885 0.022 52 / 1)',
        foreground: 'oklch(0.145 0.015 52 / 1)',
        surface: 'oklch(0.85 0.022 52 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 52 / 1)',
        accent: 'oklch(0.46 0.1079 48 / 1)',
        accentForeground: 'oklch(0.985 0.0069 48 / 1)'
      }
    },
    {
      minute: 1249,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.57671 0.01792 49.14167 / 1)',
        foreground: 'oklch(0.145 0.015 52 / 1)',
        surface: 'oklch(0.57642 0.01792 49.14167 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 52 / 1)',
        accent: 'oklch(0.46 0.1039 50.85833 / 1)',
        accentForeground: 'oklch(0.985 0.0069 48 / 1)'
      }
    },
    {
      minute: 1250,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.55154 0.01758 48.90833 / 1)',
        foreground: 'oklch(0.985 0.0068 45 / 1)',
        surface: 'oklch(0.55408 0.01758 48.90833 / 1)',
        surfaceForeground: 'oklch(0.985 0.0068 45 / 1)',
        accent: 'oklch(0.46 0.10357 51.09167 / 1)',
        accentForeground: 'oklch(0.985 0.0074 55 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.13 0.012 45 / 1)',
        foreground: 'oklch(0.985 0.0068 45 / 1)',
        surface: 'oklch(0.18 0.012 45 / 1)',
        surfaceForeground: 'oklch(0.985 0.0068 45 / 1)',
        accent: 'oklch(0.46 0.0981 55 / 1)',
        accentForeground: 'oklch(0.985 0.0074 55 / 1)'
      }
    }
  ]
});

export default nocturne;
