// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:55  dawn -> sunrise, widest step 0.033 in lightness
//   20:55  dusk -> night, widest step 0.026 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Paper — Near-achromatic surfaces (chroma <= 0.02) with a single chromatic accent. Doubles as the worked example for how fades to neutral behave.
 */
export const paper = defineThemeSystem({
  name: 'paper',
  staticThemes: {
    light: {
      background: 'oklch(0.99 0.002 95 / 1)',
      foreground: 'oklch(0.145 0.015 95 / 1)',
      surface: 'oklch(0.955 0.002 95 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 95 / 1)',
      accent: 'oklch(0.4931 0.13 260 / 1)',
      accentForeground: 'oklch(0.985 0.0061 260 / 1)'
    },
    dark: {
      background: 'oklch(0.15 0.004 260 / 1)',
      foreground: 'oklch(0.985 0.0061 260 / 1)',
      surface: 'oklch(0.2 0.004 260 / 1)',
      surfaceForeground: 'oklch(0.985 0.0061 260 / 1)',
      accent: 'oklch(0.4897 0.1193 250 / 1)',
      accentForeground: 'oklch(0.985 0.0063 250 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.004 260 / 1)',
        foreground: 'oklch(0.985 0.0061 260 / 1)',
        surface: 'oklch(0.2 0.004 260 / 1)',
        surfaceForeground: 'oklch(0.985 0.0061 260 / 1)',
        accent: 'oklch(0.4897 0.1193 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.19 0.008 270 / 1)',
        foreground: 'oklch(0.985 0.006 270 / 1)',
        surface: 'oklch(0.24 0.008 270 / 1)',
        surfaceForeground: 'oklch(0.985 0.006 270 / 1)',
        accent: 'oklch(0.4946 0.13 265 / 1)',
        accentForeground: 'oklch(0.985 0.006 265 / 1)'
      }
    },
    {
      minute: 355,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.5475 0.00708 343.33333 / 1)',
        foreground: 'oklch(0.985 0.006 270 / 1)',
        surface: 'oklch(0.55854 0.00708 343.33333 / 1)',
        surfaceForeground: 'oklch(0.985 0.006 270 / 1)',
        accent: 'oklch(0.49323 0.13 260.41667 / 1)',
        accentForeground: 'oklch(0.985 0.006 265 / 1)'
      }
    },
    {
      minute: 356,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.58 0.007 350 / 1)',
        foreground: 'oklch(0.145 0.015 70 / 1)',
        surface: 'oklch(0.5875 0.007 350 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 70 / 1)',
        accent: 'oklch(0.4931 0.13 260 / 1)',
        accentForeground: 'oklch(0.985 0.0062 255 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.97 0.006 70 / 1)',
        foreground: 'oklch(0.145 0.015 70 / 1)',
        surface: 'oklch(0.935 0.006 70 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 70 / 1)',
        accent: 'oklch(0.4916 0.13 255 / 1)',
        accentForeground: 'oklch(0.985 0.0062 255 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.99 0.002 95 / 1)',
        foreground: 'oklch(0.145 0.015 95 / 1)',
        surface: 'oklch(0.955 0.002 95 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 95 / 1)',
        accent: 'oklch(0.4931 0.13 260 / 1)',
        accentForeground: 'oklch(0.985 0.0061 260 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.96 0.006 85 / 1)',
        foreground: 'oklch(0.145 0.015 85 / 1)',
        surface: 'oklch(0.925 0.006 85 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 85 / 1)',
        accent: 'oklch(0.4925 0.13 258 / 1)',
        accentForeground: 'oklch(0.985 0.0061 258 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.94 0.01 65 / 1)',
        foreground: 'oklch(0.145 0.015 65 / 1)',
        surface: 'oklch(0.905 0.01 65 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 65 / 1)',
        accent: 'oklch(0.4905 0.1264 252 / 1)',
        accentForeground: 'oklch(0.985 0.0063 252 / 1)'
      }
    },
    {
      minute: 1255,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.57792 0.00725 349.375 / 1)',
        foreground: 'oklch(0.145 0.015 65 / 1)',
        surface: 'oklch(0.58188 0.00725 349.375 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 65 / 1)',
        accent: 'oklch(0.49013 0.12315 251.08333 / 1)',
        accentForeground: 'oklch(0.985 0.0063 252 / 1)'
      }
    },
    {
      minute: 1256,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.55158 0.00705 343.875 / 1)',
        foreground: 'oklch(0.985 0.0061 260 / 1)',
        surface: 'oklch(0.55838 0.00705 343.875 / 1)',
        surfaceForeground: 'oklch(0.985 0.0061 260 / 1)',
        accent: 'oklch(0.49011 0.12291 251.01667 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.004 260 / 1)',
        foreground: 'oklch(0.985 0.0061 260 / 1)',
        surface: 'oklch(0.2 0.004 260 / 1)',
        surfaceForeground: 'oklch(0.985 0.0061 260 / 1)',
        accent: 'oklch(0.4897 0.1193 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    }
  ]
});

export default paper;
