// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
// Background and accent arcs are design decisions; every other token is solved
// for a contrast target and clamped into the sRGB gamut, then certified across
// all 1,440 minutes by scripts/certify.mjs.
import { defineThemeSystem, holdThenSnap } from '../core.js';

/**
 * Paper — Near-achromatic surfaces (chroma <= 0.02) with a single chromatic accent. Doubles as the worked example for how fades to neutral behave.
 */
const deepNight = {
  background: 'oklch(0.15 0.004 260 / 1)',
  foreground: 'oklch(0.755 0.015 260 / 1)',
  surface: 'oklch(0.2 0.004 260 / 1)',
  surfaceForeground: 'oklch(0.7786 0.015 260 / 1)',
  accent: 'oklch(0.78 0.1 250 / 1)',
  accentForeground: 'oklch(0.3357 0.01 250 / 1)'
};

const dawn = {
  background: 'oklch(0.19 0.008 270 / 1)',
  foreground: 'oklch(0.7731 0.015 270 / 1)',
  surface: 'oklch(0.24 0.008 270 / 1)',
  surfaceForeground: 'oklch(0.8066 0.015 270 / 1)',
  accent: 'oklch(0.79 0.0908 265 / 1)',
  accentForeground: 'oklch(0.3422 0.01 265 / 1)'
};

const sunrise = {
  background: 'oklch(0.97 0.006 70 / 1)',
  foreground: 'oklch(0.3851 0.015 70 / 1)',
  surface: 'oklch(0.935 0.006 70 / 1)',
  surfaceForeground: 'oklch(0.3596 0.015 70 / 1)',
  accent: 'oklch(0.52 0.13 255 / 1)',
  accentForeground: 'oklch(1 0 255 / 1)'
};

const midday = {
  background: 'oklch(0.99 0.002 95 / 1)',
  foreground: 'oklch(0.3984 0.015 95 / 1)',
  surface: 'oklch(0.955 0.002 95 / 1)',
  surfaceForeground: 'oklch(0.3737 0.015 95 / 1)',
  accent: 'oklch(0.5 0.13 260 / 1)',
  accentForeground: 'oklch(0.9954 0.0019 260 / 1)'
};

const afternoon = {
  background: 'oklch(0.96 0.006 85 / 1)',
  foreground: 'oklch(0.3776 0.015 85 / 1)',
  surface: 'oklch(0.925 0.006 85 / 1)',
  surfaceForeground: 'oklch(0.3517 0.015 85 / 1)',
  accent: 'oklch(0.51 0.13 258 / 1)',
  accentForeground: 'oklch(1 0 258 / 1)'
};

const dusk = {
  background: 'oklch(0.94 0.01 65 / 1)',
  foreground: 'oklch(0.3633 0.015 65 / 1)',
  surface: 'oklch(0.905 0.01 65 / 1)',
  surfaceForeground: 'oklch(0.3362 0.015 65 / 1)',
  accent: 'oklch(0.52 0.13 252 / 1)',
  accentForeground: 'oklch(1 0 252 / 1)'
};

const eveningNight = {
  background: 'oklch(0.18 0.006 285 / 1)',
  foreground: 'oklch(0.7683 0.015 285 / 1)',
  surface: 'oklch(0.23 0.006 285 / 1)',
  surfaceForeground: 'oklch(0.7992 0.015 285 / 1)',
  accent: 'oklch(0.78 0.0977 255 / 1)',
  accentForeground: 'oklch(0.3348 0.01 255 / 1)'
};

export const paper = defineThemeSystem({
  name: 'paper',
  staticThemes: {
    light: midday,
    dark: deepNight
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    { minute: 0, appearance: 'dark', phase: 'night', tokens: deepNight },
    { minute: 300, appearance: 'dark', phase: 'dawn', tokens: dawn },
    // Each appearance swap occupies a single minute, so the foreground and
    // background never cross while both are on screen.
    ...holdThenSnap({
      at: 390,
      from: dawn,
      to: sunrise,
      fromAppearance: 'dark',
      toAppearance: 'light',
      phase: 'dawn',
      nextPhase: 'sunrise'
    }),
    { minute: 720, appearance: 'light', phase: 'midday', tokens: midday },
    { minute: 990, appearance: 'light', phase: 'afternoon', tokens: afternoon },
    ...holdThenSnap({
      at: 1140,
      from: dusk,
      to: eveningNight,
      fromAppearance: 'light',
      toAppearance: 'dark',
      phase: 'dusk',
      nextPhase: 'night'
    })
  ]
});

export default paper;
