// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:55  dawn -> sunrise, widest step 0.032 in lightness
//   20:54  dusk -> night, widest step 0.026 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Slate — Cool blue-grey with a restrained accent. Built for dense interfaces where the theme should stay behind the content.
 */
export const slate = defineThemeSystem({
  name: 'slate',
  staticThemes: {
    light: {
      background: 'oklch(0.978 0.006 245 / 1)',
      foreground: 'oklch(0.145 0.015 245 / 1)',
      surface: 'oklch(0.943 0.006 245 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 245 / 1)',
      accent: 'oklch(0.45 0.1 250 / 1)',
      accentForeground: 'oklch(0.985 0.0063 250 / 1)'
    },
    dark: {
      background: 'oklch(0.145 0.014 255 / 1)',
      foreground: 'oklch(0.985 0.0062 255 / 1)',
      surface: 'oklch(0.195 0.014 255 / 1)',
      surfaceForeground: 'oklch(0.985 0.0062 255 / 1)',
      accent: 'oklch(0.45 0.0888 240 / 1)',
      accentForeground: 'oklch(0.985 0.0068 240 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.145 0.014 255 / 1)',
        foreground: 'oklch(0.985 0.0062 255 / 1)',
        surface: 'oklch(0.195 0.014 255 / 1)',
        surfaceForeground: 'oklch(0.985 0.0062 255 / 1)',
        accent: 'oklch(0.45 0.0888 240 / 1)',
        accentForeground: 'oklch(0.985 0.0068 240 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.195 0.02 250 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.245 0.02 250 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.45 0.09 242 / 1)',
        accentForeground: 'oklch(0.985 0.0067 242 / 1)'
      }
    },
    {
      minute: 355,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.54563 0.01542 245.41667 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.55667 0.01542 245.41667 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.45 0.09458 244.75 / 1)',
        accentForeground: 'oklch(0.985 0.0067 242 / 1)'
      }
    },
    {
      minute: 356,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.5775 0.015 245 / 1)',
        foreground: 'oklch(0.145 0.015 240 / 1)',
        surface: 'oklch(0.585 0.015 245 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 240 / 1)',
        accent: 'oklch(0.45 0.095 245 / 1)',
        accentForeground: 'oklch(0.985 0.0064 248 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.96 0.01 240 / 1)',
        foreground: 'oklch(0.145 0.015 240 / 1)',
        surface: 'oklch(0.925 0.01 240 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 240 / 1)',
        accent: 'oklch(0.45 0.1 248 / 1)',
        accentForeground: 'oklch(0.985 0.0064 248 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.978 0.006 245 / 1)',
        foreground: 'oklch(0.145 0.015 245 / 1)',
        surface: 'oklch(0.943 0.006 245 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 245 / 1)',
        accent: 'oklch(0.45 0.1 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.955 0.01 242 / 1)',
        foreground: 'oklch(0.145 0.015 242 / 1)',
        surface: 'oklch(0.92 0.01 242 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 242 / 1)',
        accent: 'oklch(0.45 0.1 248 / 1)',
        accentForeground: 'oklch(0.985 0.0064 248 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.925 0.016 248 / 1)',
        foreground: 'oklch(0.145 0.015 248 / 1)',
        surface: 'oklch(0.89 0.016 248 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 248 / 1)',
        accent: 'oklch(0.45 0.09 244 / 1)',
        accentForeground: 'oklch(0.985 0.0066 244 / 1)'
      }
    },
    {
      minute: 1254,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.574 0.0151 251.15 / 1)',
        foreground: 'oklch(0.145 0.015 248 / 1)',
        surface: 'oklch(0.57725 0.0151 251.15 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 248 / 1)',
        accent: 'oklch(0.45 0.08946 242.2 / 1)',
        accentForeground: 'oklch(0.985 0.0066 244 / 1)'
      }
    },
    {
      minute: 1255,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.548 0.01503 251.38333 / 1)',
        foreground: 'oklch(0.985 0.0062 255 / 1)',
        surface: 'oklch(0.55408 0.01503 251.38333 / 1)',
        surfaceForeground: 'oklch(0.985 0.0062 255 / 1)',
        accent: 'oklch(0.45 0.08942 242.06667 / 1)',
        accentForeground: 'oklch(0.985 0.0068 240 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.145 0.014 255 / 1)',
        foreground: 'oklch(0.985 0.0062 255 / 1)',
        surface: 'oklch(0.195 0.014 255 / 1)',
        surfaceForeground: 'oklch(0.985 0.0062 255 / 1)',
        accent: 'oklch(0.45 0.0888 240 / 1)',
        accentForeground: 'oklch(0.985 0.0068 240 / 1)'
      }
    }
  ]
});

export default slate;
