// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:31  dawn -> sunrise, widest step 0.456 in lightness
//   20:20  dusk -> night, widest step 0.420 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Tidal — Cool arc: cyan through slate, no warm hues. For products where amber reads as a warning.
 */
export const tidal = defineThemeSystem({
  name: 'tidal',
  staticThemes: {
    light: {
      background: 'oklch(0.985 0.008 220 / 1)',
      foreground: 'oklch(0.3944 0.015 220 / 1)',
      surface: 'oklch(0.95 0.008 220 / 1)',
      surfaceForeground: 'oklch(0.3696 0.015 220 / 1)',
      accent: 'oklch(0.5 0.14 255 / 1)',
      accentForeground: 'oklch(0.997 0.0013 255 / 1)'
    },
    dark: {
      background: 'oklch(0.15 0.03 250 / 1)',
      foreground: 'oklch(0.7547 0.015 250 / 1)',
      surface: 'oklch(0.2 0.03 250 / 1)',
      surfaceForeground: 'oklch(0.7785 0.015 250 / 1)',
      accent: 'oklch(0.79 0.11 205 / 1)',
      accentForeground: 'oklch(0.3524 0.01 205 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.03 250 / 1)',
        foreground: 'oklch(0.7547 0.015 250 / 1)',
        surface: 'oklch(0.2 0.03 250 / 1)',
        surfaceForeground: 'oklch(0.7785 0.015 250 / 1)',
        accent: 'oklch(0.79 0.11 205 / 1)',
        accentForeground: 'oklch(0.3524 0.01 205 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.2 0.037 235 / 1)',
        foreground: 'oklch(0.7788 0.015 235 / 1)',
        surface: 'oklch(0.25 0.037 235 / 1)',
        surfaceForeground: 'oklch(0.8153 0.015 235 / 1)',
        accent: 'oklch(0.8 0.11 195 / 1)',
        accentForeground: 'oklch(0.3618 0.01 195 / 1)'
      }
    },
    {
      minute: 331,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.39892 0.03106 228.54167 / 1)',
        foreground: 'oklch(0.7788 0.015 235 / 1)',
        surface: 'oklch(0.42696 0.03106 228.54167 / 1)',
        surfaceForeground: 'oklch(0.8153 0.015 235 / 1)',
        accent: 'oklch(0.72767 0.1107 207.91667 / 1)',
        accentForeground: 'oklch(0.3618 0.01 195 / 1)'
      }
    },
    {
      minute: 332,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.8545 0.01745 213.75 / 1)',
        foreground: 'oklch(0.3842 0.015 210 / 1)',
        surface: 'oklch(0.83225 0.01745 213.75 / 1)',
        surfaceForeground: 'oklch(0.3588 0.015 210 / 1)',
        accent: 'oklch(0.562 0.1123 237.5 / 1)',
        accentForeground: 'oklch(1 0 245 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.97 0.014 210 / 1)',
        foreground: 'oklch(0.3842 0.015 210 / 1)',
        surface: 'oklch(0.935 0.014 210 / 1)',
        surfaceForeground: 'oklch(0.3588 0.015 210 / 1)',
        accent: 'oklch(0.52 0.1127 245 / 1)',
        accentForeground: 'oklch(1 0 245 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.985 0.008 220 / 1)',
        foreground: 'oklch(0.3944 0.015 220 / 1)',
        surface: 'oklch(0.95 0.008 220 / 1)',
        surfaceForeground: 'oklch(0.3696 0.015 220 / 1)',
        accent: 'oklch(0.5 0.14 255 / 1)',
        accentForeground: 'oklch(0.997 0.0013 255 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.955 0.014 200 / 1)',
        foreground: 'oklch(0.3734 0.015 200 / 1)',
        surface: 'oklch(0.92 0.014 200 / 1)',
        surfaceForeground: 'oklch(0.3473 0.015 200 / 1)',
        accent: 'oklch(0.51 0.1006 240 / 1)',
        accentForeground: 'oklch(1 0 240 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.925 0.022 215 / 1)',
        foreground: 'oklch(0.3518 0.015 215 / 1)',
        surface: 'oklch(0.89 0.022 215 / 1)',
        surfaceForeground: 'oklch(0.3239 0.015 215 / 1)',
        accent: 'oklch(0.52 0.1267 250 / 1)',
        accentForeground: 'oklch(1 0 250 / 1)'
      }
    },
    {
      minute: 1220,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.79583 0.02333 220.83333 / 1)',
        foreground: 'oklch(0.3518 0.015 215 / 1)',
        surface: 'oklch(0.775 0.02333 220.83333 / 1)',
        surfaceForeground: 'oklch(0.3239 0.015 215 / 1)',
        accent: 'oklch(0.565 0.12392 242.5 / 1)',
        accentForeground: 'oklch(1 0 250 / 1)'
      }
    },
    {
      minute: 1221,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.37604 0.02767 239.79167 / 1)',
        foreground: 'oklch(0.7547 0.015 250 / 1)',
        surface: 'oklch(0.40125 0.02767 239.79167 / 1)',
        surfaceForeground: 'oklch(0.7785 0.015 250 / 1)',
        accent: 'oklch(0.71125 0.11487 218.125 / 1)',
        accentForeground: 'oklch(0.3524 0.01 205 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.03 250 / 1)',
        foreground: 'oklch(0.7547 0.015 250 / 1)',
        surface: 'oklch(0.2 0.03 250 / 1)',
        surfaceForeground: 'oklch(0.7785 0.015 250 / 1)',
        accent: 'oklch(0.79 0.11 205 / 1)',
        accentForeground: 'oklch(0.3524 0.01 205 / 1)'
      }
    }
  ]
});

export default tidal;
