// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
// Background and accent arcs are design decisions; every other token is solved
// for a contrast target and clamped into the sRGB gamut, then certified across
// all 1,440 minutes by scripts/certify.mjs.
import { defineThemeSystem, holdThenSnap } from '../core.js';

/**
 * Tidal — Cool arc: cyan through slate, no warm hues. For products where amber reads as a warning.
 */
const deepNight = {
  background: 'oklch(0.15 0.03 250 / 1)',
  foreground: 'oklch(0.7547 0.015 250 / 1)',
  surface: 'oklch(0.2 0.03 250 / 1)',
  surfaceForeground: 'oklch(0.7785 0.015 250 / 1)',
  accent: 'oklch(0.79 0.11 205 / 1)',
  accentForeground: 'oklch(0.3524 0.01 205 / 1)'
};

const dawn = {
  background: 'oklch(0.2 0.037 235 / 1)',
  foreground: 'oklch(0.7788 0.015 235 / 1)',
  surface: 'oklch(0.25 0.037 235 / 1)',
  surfaceForeground: 'oklch(0.8153 0.015 235 / 1)',
  accent: 'oklch(0.8 0.11 195 / 1)',
  accentForeground: 'oklch(0.3618 0.01 195 / 1)'
};

const sunrise = {
  background: 'oklch(0.97 0.014 210 / 1)',
  foreground: 'oklch(0.3842 0.015 210 / 1)',
  surface: 'oklch(0.935 0.014 210 / 1)',
  surfaceForeground: 'oklch(0.3588 0.015 210 / 1)',
  accent: 'oklch(0.52 0.1127 245 / 1)',
  accentForeground: 'oklch(1 0 245 / 1)'
};

const midday = {
  background: 'oklch(0.985 0.008 220 / 1)',
  foreground: 'oklch(0.3944 0.015 220 / 1)',
  surface: 'oklch(0.95 0.008 220 / 1)',
  surfaceForeground: 'oklch(0.3696 0.015 220 / 1)',
  accent: 'oklch(0.5 0.14 255 / 1)',
  accentForeground: 'oklch(0.997 0.0013 255 / 1)'
};

const afternoon = {
  background: 'oklch(0.955 0.014 200 / 1)',
  foreground: 'oklch(0.3734 0.015 200 / 1)',
  surface: 'oklch(0.92 0.014 200 / 1)',
  surfaceForeground: 'oklch(0.3473 0.015 200 / 1)',
  accent: 'oklch(0.51 0.1006 240 / 1)',
  accentForeground: 'oklch(1 0 240 / 1)'
};

const dusk = {
  background: 'oklch(0.925 0.022 215 / 1)',
  foreground: 'oklch(0.3518 0.015 215 / 1)',
  surface: 'oklch(0.89 0.022 215 / 1)',
  surfaceForeground: 'oklch(0.3239 0.015 215 / 1)',
  accent: 'oklch(0.52 0.1267 250 / 1)',
  accentForeground: 'oklch(1 0 250 / 1)'
};

const eveningNight = {
  background: 'oklch(0.185 0.038 245 / 1)',
  foreground: 'oklch(0.7701 0.015 245 / 1)',
  surface: 'oklch(0.235 0.038 245 / 1)',
  surfaceForeground: 'oklch(0.8027 0.015 245 / 1)',
  accent: 'oklch(0.78 0.11 200 / 1)',
  accentForeground: 'oklch(0.3442 0.01 200 / 1)'
};

export const tidal = defineThemeSystem({
  name: 'tidal',
  staticThemes: {
    light: midday,
    dark: deepNight
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    { minute: 0, appearance: 'dark', phase: 'night', tokens: deepNight },
    { minute: 300, appearance: 'dark', phase: 'dawn', tokens: dawn },
    // Each appearance swap occupies a single minute, so the foreground and
    // background never cross while both are on screen.
    ...holdThenSnap({
      at: 390,
      from: dawn,
      to: sunrise,
      fromAppearance: 'dark',
      toAppearance: 'light',
      phase: 'dawn',
      nextPhase: 'sunrise'
    }),
    { minute: 720, appearance: 'light', phase: 'midday', tokens: midday },
    { minute: 990, appearance: 'light', phase: 'afternoon', tokens: afternoon },
    ...holdThenSnap({
      at: 1140,
      from: dusk,
      to: eveningNight,
      fromAppearance: 'light',
      toAppearance: 'dark',
      phase: 'dusk',
      nextPhase: 'night'
    })
  ]
});

export default tidal;
