// GENERATED by scripts/generate-presets.mjs — do not edit by hand.
//
// The background and accent arcs are design decisions. Every other token is
// solved for a contrast target and clamped into the sRGB gamut; where the
// theme changes polarity is solved too, by solveSchedule, rather than placed
// by hand. Certified per second by scripts/certify.mjs.
//
// Switches:
//   05:53  dawn -> sunrise, widest step 0.032 in lightness
//   20:54  dusk -> night, widest step 0.032 in lightness
import { defineThemeSystem } from '../core.js';

/**
 * Tidal — Cool arc: cyan through slate, no warm hues. For products where amber reads as a warning.
 */
export const tidal = defineThemeSystem({
  name: 'tidal',
  staticThemes: {
    light: {
      background: 'oklch(0.985 0.008 220 / 1)',
      foreground: 'oklch(0.145 0.015 220 / 1)',
      surface: 'oklch(0.95 0.008 220 / 1)',
      surfaceForeground: 'oklch(0.145 0.015 220 / 1)',
      accent: 'oklch(0.492 0.1395 255 / 1)',
      accentForeground: 'oklch(0.985 0.0062 255 / 1)'
    },
    dark: {
      background: 'oklch(0.15 0.03 250 / 1)',
      foreground: 'oklch(0.985 0.0063 250 / 1)',
      surface: 'oklch(0.2 0.03 250 / 1)',
      surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
      accent: 'oklch(0.45 0.0756 228 / 1)',
      accentForeground: 'oklch(0.985 0.0078 228 / 1)'
    }
  },
  roles: {
    pairs: [
      { bg: 'background', fg: 'foreground', min: 'AA' },
      { bg: 'surface', fg: 'surfaceForeground', min: 'AA' },
      { bg: 'accent', fg: 'accentForeground', min: 'AA' }
    ]
  },
  stops: [
    {
      minute: 0,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.03 250 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.2 0.03 250 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.45 0.0756 228 / 1)',
        accentForeground: 'oklch(0.985 0.0078 228 / 1)'
      }
    },
    {
      minute: 300,
      appearance: 'dark',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.2 0.037 235 / 1)',
        foreground: 'oklch(0.985 0.0072 235 / 1)',
        surface: 'oklch(0.25 0.037 235 / 1)',
        surfaceForeground: 'oklch(0.985 0.0072 235 / 1)',
        accent: 'oklch(0.45 0.0834 236 / 1)',
        accentForeground: 'oklch(0.985 0.0071 236 / 1)'
      }
    },
    {
      minute: 353,
      appearance: 'dark',
      phase: 'dawn',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.54008 0.02684 223.95833 / 1)',
        foreground: 'oklch(0.985 0.0072 235 / 1)',
        surface: 'oklch(0.55254 0.02684 223.95833 / 1)',
        surfaceForeground: 'oklch(0.985 0.0072 235 / 1)',
        accent: 'oklch(0.46683 0.09329 239.975 / 1)',
        accentForeground: 'oklch(0.985 0.0071 236 / 1)'
      }
    },
    {
      minute: 354,
      appearance: 'light',
      phase: 'dawn',
      tokens: {
        background: 'oklch(0.57217 0.02588 222.91667 / 1)',
        foreground: 'oklch(0.145 0.015 210 / 1)',
        surface: 'oklch(0.58108 0.02588 222.91667 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 210 / 1)',
        accent: 'oklch(0.46842 0.09423 240.35 / 1)',
        accentForeground: 'oklch(0.985 0.0065 245 / 1)'
      }
    },
    {
      minute: 420,
      appearance: 'light',
      phase: 'sunrise',
      tokens: {
        background: 'oklch(0.97 0.014 210 / 1)',
        foreground: 'oklch(0.145 0.015 210 / 1)',
        surface: 'oklch(0.935 0.014 210 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 210 / 1)',
        accent: 'oklch(0.4881 0.1058 245 / 1)',
        accentForeground: 'oklch(0.985 0.0065 245 / 1)'
      }
    },
    {
      minute: 720,
      appearance: 'light',
      phase: 'midday',
      tokens: {
        background: 'oklch(0.985 0.008 220 / 1)',
        foreground: 'oklch(0.145 0.015 220 / 1)',
        surface: 'oklch(0.95 0.008 220 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 220 / 1)',
        accent: 'oklch(0.492 0.1395 255 / 1)',
        accentForeground: 'oklch(0.985 0.0062 255 / 1)'
      }
    },
    {
      minute: 990,
      appearance: 'light',
      phase: 'afternoon',
      tokens: {
        background: 'oklch(0.955 0.014 200 / 1)',
        foreground: 'oklch(0.145 0.015 200 / 1)',
        surface: 'oklch(0.92 0.014 200 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 200 / 1)',
        accent: 'oklch(0.487 0.096 240 / 1)',
        accentForeground: 'oklch(0.985 0.0068 240 / 1)'
      }
    },
    {
      minute: 1200,
      appearance: 'light',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.925 0.022 215 / 1)',
        foreground: 'oklch(0.145 0.015 215 / 1)',
        surface: 'oklch(0.89 0.022 215 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 215 / 1)',
        accent: 'oklch(0.4897 0.1193 250 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 1254,
      appearance: 'light',
      phase: 'dusk',
      jumpAfter: true,
      tokens: {
        background: 'oklch(0.57625 0.0256 230.75 / 1)',
        foreground: 'oklch(0.145 0.015 215 / 1)',
        surface: 'oklch(0.5795 0.0256 230.75 / 1)',
        surfaceForeground: 'oklch(0.145 0.015 215 / 1)',
        accent: 'oklch(0.47184 0.09964 240.1 / 1)',
        accentForeground: 'oklch(0.985 0.0063 250 / 1)'
      }
    },
    {
      minute: 1255,
      appearance: 'dark',
      phase: 'dusk',
      tokens: {
        background: 'oklch(0.54396 0.02593 232.20833 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.55075 0.02593 232.20833 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.47018 0.09781 239.18333 / 1)',
        accentForeground: 'oklch(0.985 0.0078 228 / 1)'
      }
    },
    {
      minute: 1320,
      appearance: 'dark',
      phase: 'night',
      tokens: {
        background: 'oklch(0.15 0.03 250 / 1)',
        foreground: 'oklch(0.985 0.0063 250 / 1)',
        surface: 'oklch(0.2 0.03 250 / 1)',
        surfaceForeground: 'oklch(0.985 0.0063 250 / 1)',
        accent: 'oklch(0.45 0.0756 228 / 1)',
        accentForeground: 'oklch(0.985 0.0078 228 / 1)'
      }
    }
  ]
});

export default tidal;
